version: '2'
services:
  web:
    build:
      context: .
      args:
          CDSAGGREGATE: http://md.incommon.org/InCommon/InCommon-metadata-idp-only.xml
          CDSOVERLAYURL: https://github.com/canariecaf/cds-overlay-CAF/archive/master.zip
    command: '/start.sh'
    ports:
      - "80:80"
    
      
