version: '2'
services:
  web:
    build:
      context: .
      args:
          CDSAGGREGATE: https://caf-shib2ops.ca/CoreServices/caf_metadata_signed_sha256.xml
          CDSOVERLAYURL: https://github.com/canariecaf/cds-overlay-CAF/archive/master.zip
    command: '/start.sh'
    ports:
      - "80:80"
    
      
